# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reply History
email: replyhistory@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I run a Youtube channel called Reply History where I explain historical events with simple-to-follow diagrams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ReplyHistory
github_username:  jekyll

# Build settings
markdown: kramdown
